### ISSUE TITLE
Relationship between models

### ISSUE THREAD

**Issue by cetorres** [nickdekruijk/admin#1]
Is there a way to configure relationship between models in the admin config? Is so, how? For example: category has many product.

**Comment by nickdekruijk** [comment]
There is! You could use column type 'foreign' in the config for example:
```php
'user_id' => [
    'type' => 'foreign',
    'model' => 'App\User',
    'columns' => 'email,name',
    'scope' => 'filter',
],
```
This example will show a dropdown list that will return the id of the user model and show the email and name. The scope option allows you to have the dropdown list sorted and/or filtered (it will just add the scopeFilter() method from the model).

**Comment by cetorres** [comment]
Hi, thanks it worked. But I had to remove the 'scope' => 'filter' line. 
It crashed saying: Method Illuminate\Database\Query\Builder::filter does not exist. 
Am I doing something wrong?

**Comment by nickdekruijk** [comment]
You didn't do anything wrong, the scope is optional. Without it it just shows all rows from the model. If you had a filter scope in your model like this:
```php
public function scopeFilter($query)
{
    $query->where('active', true)->orderBy('name');
}
```
it would use that scope to show the content of the dropdown list.

**Comment by nickdekruijk** [comment]
I'll close this issue for now then. Thanks for opening the first issue btw :-)
Reminds me of starting to make some decent documentation. Please let me know what you think of this package. It's always nice to get feedback, even if it's negative (with good explanation).

**Comment by cetorres** [comment]
Hi Nick,
Thank you for your attention. You're very helpful. And the package is really great. The simplicity is the key. I was looking for something like this for my project. The only thing I'd like to see is a documentation of the admin config file with all the possible settings and their descriptions, examples etc. That'd be awesome!

**Comment by cetorres** [comment]
Could you give me an example of how to have an image field on a model and how to configure on admin config? And with multiple images, is it possible?
Thank you.
