### ISSUE TITLE
Set order of associated pivot data

### ISSUE THREAD

**Issue by cetorres** [nickdekruijk/admin#4]
Hi Nick,
Is there a way to set the order of the associated pivot data when selecting the items like this? I'd like to save the order the user clicked on the item as the order to show the items when I want in the frontend. In this case, I'm associating many categories to a business like so.

<img width="1394" alt="Screen Shot 2019-06-04 at 5 53 54 PM" src="https://user-images.githubusercontent.com/533661/58916521-e775ad00-86f1-11e9-8ca3-43b85d97d023.png">

I'd like to know if I can save the order that the user clicked on the categories to be the order I will show in the frontend. Or if there's another way to drag'n'drop to reorder the categories there to reflect the order they will be associated to the business when I show in the business profile.

Currently, I'm showing as alphabetical order on admin and frontend. But I'd like to have the order of the associated categories set differently for each business.

This is how I have configured on the admin.php, inside my Businesses module:
```php
'categories' => [
   'validate' => 'required',
   'type' => 'pivot',
   'model' => 'App\Category',
   'columns' => 'name_en',
   'scope' => 'filter',
], 
```

Thank you.

**Comment by nickdekruijk** [comment]
I use the scope for that. Add ->orderBy('nane') to your filter scope

**Comment by cetorres** [comment]
I'm doing that on the scope already for alphabetical order of the name of the category as I said. But that orderBy sorts the categories on the admin and on the business page (front end) in a global way. What I need to do is to set a specific order of the categories for each business.

Example: For a business MyBusiness, I associate category D, E, A. Right now it appears on front end as A, D, E. I'd like to keep the order I associated these categories for this business to show as D, E, A.
Got it?

**Comment by cetorres** [comment]
Normally I would do this using a relational attribute for the sort_order in the relational table business_category. That has business_id, category_id and would add sort_order with integers to get the order and show on frontend. But with your admin and Laravel I'm unsure how to do it.

**Comment by nickdekruijk** [comment]
Ah, now I get what you mean. Unfortunately that's not possible right now. And since I don't need that feature myself I'll not invest too much time in it.

**Comment by cetorres** [comment]
I'm doing something simple but that will solve it. The only thing I'd need is to save the category list in the same order that the user selects them on the admin interface. Because I'm now saving an id (auto-incremented) for the relationships. If I could guarantee the order of saving, then the id would be my ordering attributes and then I can obtain the list of categories ordering by it.
So my question is, is there a way to save the categories in the order the user selects it using the admin interface for selecting pivot data (above)? How are you saving right now?
Thanks.

**Comment by nickdekruijk** [comment]
All pivot items are just checkboxes behind the scenes `<input type="checkbox" class="pivot-tags" name="tags[]" value="3">` so they are submitted as an array and stored in the same order as they are in the array.

**Comment by cetorres** [comment]
Ok, I'll take a look. Thanks.
Another quick question. Is there a way to enable pagination on an admin module list?

**Comment by nickdekruijk** [comment]
Nope. Personally I hate pagination. Unless I had thousands of entries I wouldn't use it.
